---
title: "Final Project"
author: "Robert_Ukamaka_Clayton"
date: "November 17, 2021"
output: html_document
---


## Linear Regression

The main cost function we are trying to minimize.
```{r}
# defining the cost function
minimize = function(y, X, beta0) {
  R <- sum((y - X%*%beta0)^2)
}
```

```{r our_lm}
our_lm = function(y, X, alpha = 0.05) {
  
  # Make sure data formats are appropriate
  y <- as.vector(y)
  X <- as.matrix(X)
  
  # Define parameters
  n <- length(y)
  p <- dim(X)[2]
  df <- n - p
  
  beta0 <- rep(NA, ncol(X))
  beta0[1] <- mean(y)
  
  for (i in 2:ncol(X)){ 
    beta0[i] <- cov(X[,i],y)/var(X[,i])
  }
  
  # Estimate beta
  m <- optim(par = beta0, fn = minimize, y = y, X = X)
  beta.hat <- m$par
  
  # Checking fitness of the model
  y_hat  <- X%*%beta.hat
  SSE <- sum((y - y_hat)^2)
  SST <- sum((y - mean(y))^2)
  R_sq <- 1 - (SSE/SST)  #coefficient of determination
  
  #computing the residuals
  resid <- y - X%*%as.matrix(beta.hat)
  sigma2.hat <- (i/df) * t(resid) %*% resid
  Cp <- SSE + 2*p*sigma2.hat #Mallow's Cp
  
  var.beta <- drop(sigma2.hat) * solve(t(X)%*%X)
  
  # Confidence intervals for beta
  quant <- 1 - alpha/2
  ci.beta <- c(beta.hat - qnorm(p = quant)*sqrt(var.beta), beta.hat + qnorm(p = quant)*sqrt(var.beta))
  
  # F-test
  DFM <- p - 1
  DFE <- n - p
  SSM <- sum((y_hat - mean(y))^2)
  MSM <- SSM/DFM
  MSE <- SSE / DFE
  
  F_star <- MSM/MSE
  p <- pf(F_star, DFM, DFE, lower.tail = FALSE)
  
  # Return all estimated values
  return(list(beta = beta.hat, sigma2 = sigma2.hat, variance_beta = var.beta,
              r_squared = R_sq, mallow = Cp, f_stat = F_star, p_value = p, 
              ci = ci.beta, res = resid, preds = y_hat))
}

```


<<<<<<< HEAD
```{r initialize, results=TRUE}
df <- read.csv2("bank.csv", header = TRUE)
df$job <- as.numeric(as.factor(df$job))
df$marital <- as.numeric(as.factor(df$marital))
df$education <- as.numeric(as.factor(df$education))
df$default <- as.numeric(as.factor(df$default))
df$housing <- as.numeric(as.factor(df$housing))
df$loan <- as.numeric(as.factor(df$loan))
df$contact <- as.numeric(as.factor(df$contact))
df$month <- as.numeric(as.factor(df$month))
df$poutcome <- as.numeric(as.factor(df$poutcome))
df$y <- as.numeric(as.factor(df$y))

x <- df[, -which(names(df) == "y")]
y <- df$y
model <- our_lm(y, x, alpha = 0.05)
model$variance_beta
=======
```{r initialize}
x <- matrix(rnorm(400), ncol = 4) # so this is a 100x4 predictor matrix 
y <- rnorm(100)
model <- our_lm(y, x, alpha = 0.05)
model
>>>>>>> main
```


```{r res_plot}
res_plot <- function(res, preds){
  plot(preds, res, main = "Residuals vs Fitted Values",
        xlab="Fitted Values", ylab="Residuals")
  abline(0,0)
}
```


```{r qqplot}
qq_plot <- function(res){
  qqnorm(res)
  qqline(res)
}
```

```{r hist}
histogram <- function(res){
  hist(res, main = "Histogram of Residuals", xlab = "Residuals")
}
```


